### ISSUE TITLE
SubAccounts Not Working 

### ISSUE THREAD

**Issue by emmanuel-libertechy** [Flutterwave/Flutterwave-Angular-v3#9] opened 2021-04-26 22:58 UTC
Hello,
Can you please confirm that the subaccount feature is working using Method 2 (Promise): Async Payment Response. I did several tests but the split didn't happen. Awaiting your quick response

Regards,
Emmanuel

**Comment by toybz** [comment] 2021-05-10 07:57
Hello @emmanuel-libertechy  
Apologies for the late response, 
kindly confirm if you still experience this issue.
If yes, please share your payment payload.

**Comment by emmanuel-libertechy** [comment] 2021-05-10 09:20
Hello @toybz ,
I just tested again now and the issue remains - payment successful but splitting not done. Kindly see below details of payload and success response of transaction.

Payload
{
amount: 120
currency: "NGN"
customer: {name: "Emmanuel XXXXXXXX", email: "emmanuel*******@gmail.com", phonenumber: "08100000000", phone_number: "080****"}
customizations: {title: "Arrive NG (By Applicentric)", description: "Payment for Ekwulobia - Lagos trip by Emmanuel Ade…bigbe and others - 1 passengers on the 30/04/2021"}
onclose: function()
payment_options: "card,ussd"
public_key: "FLWPUBK-e86be058a17c651afe08337e9f4d66f0-X"
redirect_url: ""
subaccounts: [{id: "RS_3FE70300941450CB3A7F258F3C89BBD4"}] (1)
tx_ref: "dev_0dee1a6e-53b9-0918-5c63-3367e48011cc"
}
Success Response
{
amount: 120

currency: "NGN"

customer: {name: undefined, email: undefined, phone_number: undefined}

flw_ref: "ApplicentricLim/PO58617359574"

status: "successful"
transaction_id: 425202725
tx_ref: "dev_0dee1a6e-53b9-0918-5c63-3367e48011cc"
}

Regards,
Emmanuel

**Comment by emmanuel-libertechy** [comment] 2021-05-10 10:29
Hello,
Kindly see the payload of further tests done. Payments were successful but splitting didn't happen

<img width="798" alt="Screenshot 2021-05-10 at 11 22 54" src="https://user-images.githubusercontent.com/57720402/117645796-e6254880-b182-11eb-95a7-6fee47d8f84a.png">
<img width="803" alt="Screenshot 2021-05-10 at 11 18 36" src="https://user-images.githubusercontent.com/57720402/117645813-eb829300-b182-11eb-8fbe-debd208872fe.png">

**Comment by toybz** [comment] 2022-02-03 11:44
Closing this issue because it's not caused by the plugin. We have tested severally and splitting works as expected using the plugin.

**Closed by toybz** 2022-02-03 11:44 UTC
